on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.98.1
          target: wasm32-unknown-unknown
          override: true
          components: clippy
      - run: cargo install wasm-pack --version 0.15.1
